### ISSUE TITLE
Add A License

### ISSUE THREAD

**Issue by bonedaddy** [cdipaolo/sentiment#11]
If possible please add a license, otherwise you are not legally allowed to use this code in other libraries

**Comment by cdipaolo** [comment]
Hi, fixed -- see https://github.com/cdipaolo/sentiment/commit/c697f64e7f10fd01c27c582fbd0101ea895a75dc

I already said something to the effect of "it's MIT" in the README but understand if there are legal reasons the full text is better, thanks for bringing this up! https://github.com/cdipaolo/sentiment/tree/master#license---mit
